nodes:
 -
   mysql:
   host: "127.0.0.1"
   user: root
   password: 123456
   db: test
   tables:
    -
   table_1
    -
   table_2
  consumers:
   -
   url: "http://www.baidu.com"
    tables:
     -
   table_1
   -
   url: "http://www.baidu1.com"
    tables:
     -
   table_2
 -
   mysql:
   host: "127.0.0.1"
   user: root
   password: 123456
   db: test
   tables:
    -
   table_1
    -
   table_2
  consumers:
   -
   url: "http://www.baidu.com"
    tables:
     -
   table_1
   -
   url: "http://www.baidu1.com"
    tables:
     -
   table_2